# log level configration
# possible levels: SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST
# all other inputs or missing entry will default to ALL
logLevel.reCall=FINE
logLevel.goCat=FINE
logLevel.idGenerator=FINE
logLEvel.server=FINE
logLevel.reCallAudi=FINE

# enabling different generators
enable.recall=enabled
enable.gocat=enabled
enable.idgenerator=enabled

# setting parameter for server startup
# IP for Demo_ECE
server.url=https://172.29.209.145
#server.url=https://172.29.210.98
# IP for local unit tests
#server.url=http://localhost
server.port=21000

# target environment is for ID generator
# and means
# Web Centre:
# DEMO_ECE
server.target.environment=http://mbbonup-mgmt04demo.lb-xfer-tui.web.audi.vwg/onup/api/bs/oru/v1/
# APPROVAL_ECE
#server.target.environment=http://mbbonup-mgmt04appr.lb-xfer-pre.web.audi.vwg/onup/api/bs/oru/v1/
# ODP
# DEMO_ODP
#server.target.environment=https://mbbonupadmin.moria.dmo.apl.eu.dp.odp.cloud.vwgroup.com/onup/api/bs/oru/v1/
# APPROVAL_ODP
#server.target.environment=https://mbbonupadmin.moria.app.apl.eu.dp.odp.cloud.vwgroup.com/onup/api/bs/oru/v1/