/**
 *
 */
package de.sulzer.pages.util.constants;

/**
 * @author Sulzer GmbH
 *
 */
public final class ConstantsRoles {

	// root role
	public static final String OU_ROLE_ROOT = "OU_ROLE_ROOT";

	/*
	 * Roles & Rights - accumulated rights
	 */
	public static final String FACHLICHER_ADMINISTRATOR = "FACHLICHER_ADMINISTRATOR";
	public static final String TECHNISCHER_REDAKTEUR_GS = "TECHNISCHER_REDAKTEUR_GS";
	public static final String TECHNISCHER_REDAKTEUR_MAPPING = "TECHNISCHER_REDAKTEUR_MAPPING";

	/*
	 * Roles & Rights
	 */
	public static final String OU_ROLE_SULZER_ORU_BATCH_MOVE = "OU_ROLE_SULZER_ORU_BATCH_MOVE";

	public static final String OU_ROLE_SULZER_ORU_BATCH_APPROVE_STOP = "OU_ROLE_SULZER_ORU_BATCH_APPROVE_STOP";

	public static final String OU_ROLE_SULZER_ORU_SEARCH_ENTRY_EDIT = "OU_ROLE_SULZER_ORU_SEARCH_ENTRY_EDIT";

	public static final String OU_ROLE_SULZER_ORU_VIEW = "OU_ROLE_SULZER_ORU_VIEW";

	public static final String OU_ROLE_SULZER_ORU_BATCH_DELETE = "OU_ROLE_SULZER_ORU_BATCH_DELETE";

	public static final String OU_ROLE_SULZER_ORU_BATCH_CREATE_EDIT = "OU_ROLE_SULZER_ORU_BATCH_CREATE_EDIT";

	public static final String OU_ROLE_SULZER_ORU_ARCHIVE = "OU_ROLE_SULZER_ORU_ARCHIVE";

	public static final String OU_ROLE_SULZER_ORU_INBOX_EXISTING_OVERVIEW = "OU_ROLE_SULZER_ORU_INBOX_EXISTING_OVERVIEW";

	public static final String OU_ROLE_SULZER_ORU_INBOX_ARCHIVED_OVERVIEW = "OU_ROLE_SULZER_ORU_INBOX_ARCHIVED_OVERVIEW";

	public static final String OU_ROLE_SULZER_ORU_CRITERION_ADD = "OU_ROLE_SULZER_ORU_CRITERION_ADD";

	public static final String OU_ROLE_SULZER_ORU_SEARCH_OVERVIEW = "OU_ROLE_SULZER_ORU_SEARCH_OVERVIEW";

	public static final String OU_ROLE_SULZER_EDIT_ROLE = "OU_ROLE_SULZER_EDIT_ROLE";

	public static final String OU_ROLE_SULZER_ORU_DL_SECURITY_INFO = "OU_ROLE_SULZER_ORU_DL_SECURITY_INFO";

	public static final String OU_ROLE_SULZER_ORU_SAVE_CHANGES = "OU_ROLE_SULZER_ORU_SAVE_CHANGES";

	public static final String OU_ROLE_SULZER_ORU_TRANSLATION_SETTINGS = "OU_ROLE_SULZER_ORU_TRANSLATION_SETTINGS";

	public static final String OU_ROLE_SULZER_ORU_TRANSLATION_SETTINGS_EDIT = "OU_ROLE_SULZER_ORU_TRANSLATION_SETTINGS_EDIT";

	public static final String OU_ROLE_SULZER_ORU_TRANSLATION_ORDER_GOCAT = "OU_ROLE_SULZER_ORU_TRANSLATION_ORDER_GOCAT";

	public static final String OU_ROLE_SULZER_ORU_CRITERION_DELETE = "OU_ROLE_SULZER_ORU_CRITERION_DELETE";

	public static final String OU_ROLE_SULZER_ORU_FLASHMEDIUM_ADD = "OU_ROLE_SULZER_ORU_FLASHMEDIUM_ADD";

	public static final String OU_ROLE_SULZER_ORU_FLASHMEDIUM_DELETE = "OU_ROLE_SULZER_ORU_FLASHMEDIUM_DELETE";

	public static final String OU_ROLE_SULZER_ORU_INBOX_SEE_IMP_RC = "OU_ROLE_SULZER_ORU_INBOX_SEE_IMP_RC";

	public static final String OU_ROLE_SULZER_ORU_INBOX_CREATE_NEW_ORU = "OU_ROLE_SULZER_ORU_INBOX_CREATE_NEW_ORU";

	public static final String OU_ROLE_SULZER_ORU_SEARCH_ENTRY_DELETE = "OU_ROLE_SULZER_ORU_SEARCH_ENTRY_DELETE";

	/*
	 * ORU Rollout Status
	 */
	public static final String OU_ROLE_SULZER_CAMP_PROCESS_OVERVIEW = "OU_ROLE_SULZER_CAMP_PROCESS_OVERVIEW";

	/*
	 * Roles & Rights - Service42
	 */

	public static final String OU_ROLE_SULZER_ORU_INBOX_SEE_MAN_S42 = "OU_ROLE_SULZER_ORU_INBOX_SEE_MAN_S42";

	public static final String OU_ROLE_SULZER_ORU_INBOX_USE_MAN_S42 = "OU_ROLE_SULZER_ORU_INBOX_USE_MAN_S42";

	public static final String OU_ROLE_SULZER_ORU_INBOX_SEE_IMP_S42 = "OU_ROLE_SULZER_ORU_INBOX_SEE_IMP_S42";

	public static final String OU_ROLE_SULZER_ORU_INBOX_USE_IMP_S42 = "OU_ROLE_SULZER_ORU_INBOX_USE_IMP_S42";

	public static final String OU_ROLE_SULZER_TST_S42_ENTRY_FM_DELETE = "OU_ROLE_SULZER_TST_S42_ENTRY_FM_DELETE";

	public static final String OU_ROLE_SULZER_TST_S42_ENTRY_DELETE = "OU_ROLE_SULZER_TST_S42_ENTRY_DELETE";

	public static final String OU_ROLE_SULZER_TST_S42_ENTRY_CREATE = "OU_ROLE_SULZER_TST_S42_ENTRY_CREATE";

	public static final String OU_ROLE_SULZER_TST_S42_OVERVIEW = "OU_ROLE_SULZER_TST_S42_OVERVIEW";

	public static final String OU_ROLE_SULZER_TST_S42_ENTRY_EDIT = "OU_ROLE_SULZER_TST_S42_ENTRY_EDIT";

	/*
	 * Roles & Rights - Campaign History
	 */

	public static final String OU_ROLE_SULZER_MBT_CALC_VIEW = "OU_ROLE_SULZER_MBT_CALC_VIEW";

	public static final String OU_ROLE_SULZER_VO_CAMP_HISTORY_REWIND = "OU_ROLE_SULZER_VO_CAMP_HISTORY_REWIND";

	public static final String OU_ROLE_SULZER_VO_CAMP_HISTORY_VIEW = "OU_ROLE_SULZER_VO_CAMP_HISTORY_VIEW";

	public static final String OU_ROLE_SULZER_VO_ACTIVE_CAMP_NOTIFY = "OU_ROLE_SULZER_VO_ACTIVE_CAMP_NOTIFY";

	public static final String OU_ROLE_SULZER_VO_ACTIVE_CAMP_ABORT = "OU_ROLE_SULZER_VO_ACTIVE_CAMP_ABORT";

	public static final String OU_ROLE_SULZER_VO_ACTIVE_CAMP_VIEW = "OU_ROLE_SULZER_VO_ACTIVE_CAMP_VIEW";

	public static final String OU_ROLE_SULZER_VO_ACTIVE_CAMP_FORCE_ABORT = "OU_ROLE_SULZER_VO_ACTIVE_CAMP_FORCE_ABORT";

	public static final String OU_ROLE_SULZER_VO_SCHED_CAMP_VIEW = "OU_ROLE_SULZER_VO_SCHED_CAMP_VIEW";

	public static final String OU_ROLE_SULZER_VO_SCHED_CAMP_ABORT = "OU_ROLE_SULZER_VO_SCHED_CAMP_ABORT";

	public static final String OU_ROLE_SULZER_VO_VC_MIB_VIEW = "OU_ROLE_SULZER_VO_VC_MIB_VIEW";

	public static final String OU_ROLE_SULZER_VO_VC_CGW_VIEW = "OU_ROLE_SULZER_VO_VC_CGW_VIEW";

	public static final String OU_ROLE_SULZER_VO_SEARCH = "OU_ROLE_SULZER_VO_SEARCH";

	public static final String OU_ROLE_SULZER_VO_VC_MIB_RESET = "OU_ROLE_SULZER_VO_VC_MIB_RESET";

	public static final String OU_ROLE_SULZER_VO_VC_CGW_RESET = "OU_ROLE_SULZER_VO_VC_CGW_RESET";

	public static final String OU_ROLE_SULZER_VO_VC_OCU2_RESET = "OU_ROLE_SULZER_VO_VC_OCU2_RESET";

	public static final String OU_ROLE_SULZER_VO_CARPORT_VIEW = "OU_ROLE_SULZER_VO_CARPORT_VIEW";

	public static final String OU_ROLE_SULZER_VO_CARPORT_FETCH = "OU_ROLE_SULZER_VO_CARPORT_FETCH";

	/*
	 * Roles & Rights - User List Export
	 */

	public static final String OU_ROLE_SULZER_EXPORT_USER = "OU_ROLE_SULZER_EXPORT_USER";

	public static final String OU_ROLE_SULZER_COPY_ROLES = "OU_ROLE_SULZER_COPY_ROLES";

	/*
	 * Roles & Rights - User configuration
	 */
	public static final String OU_ROLE_SULZER_VIEW_CONFIG = "OU_ROLE_SULZER_VIEW_CONFIG";

	public static final String OU_ROLE_SULZER_RELOAD_CONFIG = "OU_ROLE_SULZER_RELOAD_CONFIG";

	/*
	 * Roles & Rights - Log Overview
	 */

	public static final String OU_ROLE_SULZER_LOG_OVERVIEW = "OU_ROLE_SULZER_LOG_OVERVIEW";

	public static final String OU_ROLE_SULZER_ORU_INBOX_OVERVIEW = "OU_ROLE_SULZER_ORU_INBOX_OVERVIEW";

	public static final String OU_ROLE_SULZER_EL_OVERVIEW = "OU_ROLE_SULZER_EL_OVERVIEW";

	public static final String OU_ROLE_SULZER_TEMP_OVERVIEW = "OU_ROLE_SULZER_TEMP_OVERVIEW";

	public static final String OU_ROLE_SULZER_EL_ENTRY_CREATE = "OU_ROLE_SULZER_EL_ENTRY_CREATE";

	public static final String OU_ROLE_SULZER_EL_ENTRY_EDIT = "OU_ROLE_SULZER_EL_ENTRY_EDIT";

	public static final String OU_ROLE_SULZER_EL_ENTRY_DELETE = "OU_ROLE_SULZER_EL_ENTRY_DELETE";

	public static final String OU_ROLE_SULZER_TEMP_ENTRY_EDIT = "OU_ROLE_SULZER_TEMP_ENTRY_EDIT";

	public static final String OU_ROLE_SULZER_TEMP_ENTRY_CREATE = "OU_ROLE_SULZER_TEMP_ENTRY_CREATE";

	public static final String OU_ROLE_SULZER_TEMP_ENTRY_DELETE = "OU_ROLE_SULZER_TEMP_ENTRY_DELETE";

	/*
	 * Vehicle Administration
	 */

	public static final String OU_ROLE_SULZER_VO_OPTIONS_VIEW = "OU_ROLE_SULZER_VO_OPTIONS_VIEW";

	public static final String OU_ROLE_SULZER_VO_OPTIONS_EDIT = "OU_ROLE_SULZER_VO_OPTIONS_EDIT";

	public static final String OU_ROLE_SULZER_VO_VC_OCU2_VIEW = "OU_ROLE_SULZER_VO_VC_OCU2_VIEW";

	/*
	 * Sector Logs
	 */

	public static final String OU_ROLE_SULZER_LOG_REPORTING = "OU_ROLE_SULZER_LOG_REPORTING";

	public static final String OU_ROLE_SULZER_OVERVIEW_DELETE = "OU_ROLE_SULZER_OVERVIEW_DELETE";

	public static final String OU_ROLE_SULZER_DETAIL_VIEW = "OU_ROLE_SULZER_DETAIL_VIEW";

	public static final String OU_ROLE_SULZER_DETAIL_DELETE = "OU_ROLE_SULZER_DETAIL_DELETE";

	/*
	 * Roles & Rights - Pending Campaign
	 */

	public static final String OU_ROLE_SULZER_VO_PEND_CAMP_VIEW = "OU_ROLE_SULZER_VO_PEND_CAMP_VIEW";

	public static final String OU_ROLE_SULZER_VO_PEND_CAMP_ABORT = "OU_ROLE_SULZER_VO_PEND_CAMP_ABORT";

	/*
	 * Roles & rights - ReCall
	 */
	public static final String OU_ROLE_SULZER_RECALL_EDIT = "OU_ROLE_SULZER_RECALL_EDIT";

	public static final String OU_ROLE_SULZER_RECALL_VIEW_VEHICLE_DETAILS = "OU_ROLE_SULZER_RECALL_VIEW_VEHICLE_DETAILS";

	public static final String OU_ROLE_SULZER_RECALL_DELETE = "OU_ROLE_SULZER_RECALL_DELETE";

	public static final String OU_ROLE_SULZER_RECALL_OVERVIEW = "OU_ROLE_SULZER_RECALL_OVERVIEW";

	public static final String OU_ROLE_SULZER_RECALL_CREATE = "OU_ROLE_SULZER_RECALL_CREATE";

	/*
	 * Roles & Rights - Status Report
	 */

	public static final String OU_SULZER_STATUS_REPORT_MENU = "OU_SULZER_STATUS_REPORT_MENU";

	public static final String OU_SULZER_STATUS_REPORT_VIEW = "OU_SULZER_STATUS_REPORT_VIEW";

	public static final String OU_SULZER_STATUS_REPORT_DOWNLOAD = "OU_SULZER_STATUS_REPORT_DOWNLOAD";

	public static final String OU_SULZER_STATUS_REPORT_CREATE = "OU_SULZER_STATUS_REPORT_CREATE";

	public static final String OU_SULZER_STATUS_REPORT_DELETE = "OU_SULZER_STATUS_REPORT_DELETE";

	/*
	 * Roles & Rights - ORI Campaign deletion (not yet approved)
	 */
	public static final String OU_ROLE_SULZER_ORU_CAMPAIGN_DELETE = "OU_ROLE_SULZER_ORU_CAMPAIGN_DELETE";

	/*
	 * Roles & Rights - Configuration List
	 */
	public static final String OU_ROLE_SULZER_CONFIGURATION_CLEAR_DWH = "OU_ROLE_SULZER_CONFIGURATION_CLEAR_DWH";

	public static final String OU_ROLE_SULZER_CONFIGURATION_VIEW = "OU_ROLE_SULZER_CONFIGURATION_VIEW";

	public static final String OU_ROLE_SULZER_CONFIGURATION_CHANGE_USER = "OU_ROLE_SULZER_CONFIGURATION_CHANGE_USER";

	public static final String OU_ROLE_SULZER_CONFIGURATION_CHANGE_UNBLOCKING = "OU_ROLE_SULZER_CONFIGURATION_CHANGE_UNBLOCKING";

	/*
	 * Roles & Rights - Documentation
	 */
	public static final String OU_ROLE_SULZER_DOCOVERVIEW_RECALL = "OU_ROLE_SULZER_DOCOVERVIEW_RECALL";

	public static final String OU_ROLE_SULZER_DOCOVERVIEW_RECALL_RETRY = "OU_ROLE_SULZER_DOCOVERVIEW_RECALL_RETRY";

	public static final String OU_ROLE_SULZER_DOCOVERVIEW_RECALL_SUCCESS = "OU_ROLE_SULZER_DOCOVERVIEW_RECALL_SUCCESS";

	public static final String OU_ROLE_SULZER_DOCOVERVIEW_CARPORT = "OU_ROLE_SULZER_DOCOVERVIEW_CARPORT";

	public static final String OU_ROLE_SULZER_DOCOVERVIEW_CARPORT_RETRY = "OU_ROLE_SULZER_DOCOVERVIEW_CARPORT_RETRY";

	public static final String OU_ROLE_SULZER_DOCOVERVIEW_CARPORT_SUCCESS = "OU_ROLE_SULZER_DOCOVERVIEW_CARPORT_SUCCESS";

}
